name: My first workflow
on: push
jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Copy code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Run build
        run: npm run build
